import Header from '@/components/header/Header'
import '../globals.css'
import '../bottomSheet.css'
import Providers from '@/utils/provider'
import Profile from '@/components/header/Profile'


export const metadata = {
  title: 'Menu',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa" className='main'>
      <body className='bg-background max-w-[480px] m-auto'>
        <Providers>
          <Profile />
          <div className='sticky top-0 z-10 bg-background py-[16px]'>
            <Header />
          </div>
          {children}
        </Providers>
      </body>
    </html>
  )
}
